"use client"

import { useEffect, useState } from "react"
import { useParams, useRouter } from "next/navigation"
import type { Shipment } from "@/types"
import { LocalStorage } from "@/lib/storage"
import { ProgressStepper } from "@/components/shipment/progress-stepper"
import { ShipmentDetailsCard } from "@/components/shipment/shipment-details-card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { ArrowLeft, FileText, Upload } from "lucide-react"
import Link from "next/link"

export default function PreArrivalValidationPage() {
  const params = useParams()
  const router = useRouter()
  const [shipment, setShipment] = useState<Shipment | null>(null)

  useEffect(() => {
    const shipments = LocalStorage.getShipments()
    const found = shipments.find((s) => s.id === params.id)
    if (found) setShipment(found)
  }, [params.id])

  if (!shipment) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-gray-600">Loading...</div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Breadcrumb */}
      <div className="bg-white border-b border-gray-200 px-6 py-4">
        <div className="flex items-center gap-2 text-sm text-gray-600">
          <Link href="/" className="hover:text-gray-900">
            Shipment
          </Link>
          <span>/</span>
          <Link href={`/shipments/${shipment.id}`} className="hover:text-gray-900">
            Shipment {shipment.shipmentNumber}
          </Link>
          <span>/</span>
          <span className="text-gray-900 font-medium">Pre-Arrival Validation</span>
        </div>
      </div>

      {/* Progress Stepper */}
      <ProgressStepper currentStatus={shipment.status} stages={shipment.stages} shipmentId={shipment.id} />

      {/* Main Content */}
      <div className="max-w-7xl mx-auto px-6 py-8">
        <div className="mb-6">
          <Button variant="outline" onClick={() => router.push(`/shipments/${shipment.id}`)} className="gap-2">
            <ArrowLeft className="w-4 h-4" />
            Back to Shipment
          </Button>
        </div>

        <ShipmentDetailsCard shipment={shipment} />

        {/* Header with Status Badge */}
        <div className="bg-gradient-to-r from-blue-50 to-indigo-50 border border-blue-200 rounded-lg p-4 mt-6 mb-6 flex items-start gap-3">
          <div className="w-8 h-8 bg-blue-500 rounded-full flex items-center justify-center flex-shrink-0 text-white font-bold">
            3
          </div>
          <div className="flex-1">
            <div className="flex items-center gap-2 mb-2">
              <h1 className="text-lg font-semibold text-gray-900">Pre-Arrival Validation</h1>
              <Badge variant="default" className="bg-green-600 text-white border-green-700">
                Acknowledged by PortNet
              </Badge>
            </div>
            <p className="text-sm text-gray-700">
              Validate all documents and verify cargo manifest against PortNet Summary before Unberthing
            </p>
          </div>
        </div>

        {/* Documents Section */}
        <div className="bg-white rounded-lg border border-gray-200 p-6 mb-6">
          <div className="flex items-center gap-2 mb-4">
            <FileText className="w-5 h-5 text-gray-700" />
            <h2 className="text-lg font-semibold text-gray-900">Documents</h2>
          </div>

          <div className="overflow-x-auto mb-6">
            <table className="w-full">
              <thead>
                <tr className="border-b border-gray-200">
                  <th className="text-left py-3 px-4 text-sm font-semibold text-gray-900">Document Name</th>
                  <th className="text-left py-3 px-4 text-sm font-semibold text-gray-900">AI Confidence Score (Extraction)</th>
                  <th className="text-left py-3 px-4 text-sm font-semibold text-gray-900">Last Updated</th>
                  <th className="text-left py-3 px-4 text-sm font-semibold text-gray-900">Actions</th>
                </tr>
              </thead>
              <tbody>
                <tr className="border-b border-gray-100">
                  <td className="py-3 px-4 text-sm text-gray-900">Cargo Manifest</td>
                  <td className="py-3 px-4">
                    <span className="text-sm text-gray-600 bg-gray-100 px-3 py-1 rounded">NA, generated by system</span>
                  </td>
                  <td className="py-3 px-4 text-sm text-gray-900">21/09/2025 17:00</td>
                  <td className="py-3 px-4">
                    <div className="flex gap-2 text-sm">
                      <Button variant="link" size="sm" className="text-blue-600 p-0 h-auto">
                        View/Edit
                      </Button>
                      <span className="text-gray-300">|</span>
                      <Button variant="link" size="sm" className="text-blue-600 p-0 h-auto">
                        Download
                      </Button>
                      <span className="text-gray-300">|</span>
                      <Button variant="link" size="sm" className="text-red-600 p-0 h-auto">
                        Delete
                      </Button>
                    </div>
                  </td>
                </tr>
                <tr className="border-b border-gray-100">
                  <td className="py-3 px-4 text-sm text-gray-900">PortNet Summary</td>
                  <td className="py-3 px-4">
                    <div className="flex items-center gap-2">
                      <div className="flex-1 h-2 bg-gray-200 rounded-full overflow-hidden max-w-[200px]">
                        <div className="h-full bg-green-500" style={{ width: "100%" }} />
                      </div>
                      <span className="text-sm text-gray-900 font-medium">100</span>
                    </div>
                  </td>
                  <td className="py-3 px-4 text-sm text-gray-900">21/09/2025 17:00</td>
                  <td className="py-3 px-4">
                    <div className="flex gap-2 text-sm">
                      <Button variant="link" size="sm" className="text-blue-600 p-0 h-auto">
                        View/Edit
                      </Button>
                      <span className="text-gray-300">|</span>
                      <Button variant="link" size="sm" className="text-blue-600 p-0 h-auto">
                        Download
                      </Button>
                      <span className="text-gray-300">|</span>
                      <Button variant="link" size="sm" className="text-red-600 p-0 h-auto">
                        Delete
                      </Button>
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>

          {/* Action Buttons */}
          <div className="flex items-center justify-between">
            <div className="flex gap-3">
              <Button className="gap-2">
                <Upload className="w-4 h-4" />
                Upload Document
              </Button>
              <Button variant="outline">Request PortNet Summary Resubmission</Button>
            </div>
            <Button variant="outline" asChild>
              <Link href={`/shipments/${shipment.id}/audit`}>View Audit Trail</Link>
            </Button>
          </div>
        </div>

        {/* Document Validation Table */}
        <div className="bg-white rounded-lg border border-gray-200 p-6 mb-6">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="border-b border-gray-200">
                  <th className="text-left py-3 px-4 text-sm font-semibold text-gray-900">Cargo Manifest</th>
                  <th className="text-left py-3 px-4 text-sm font-semibold text-gray-900">PortNet Summary</th>
                  <th className="text-left py-3 px-4 text-sm font-semibold text-gray-900">AI Match Score</th>
                  <th className="text-left py-3 px-4 text-sm font-semibold text-gray-900">Errors</th>
                  <th className="text-left py-3 px-4 text-sm font-semibold text-gray-900">Actions</th>
                </tr>
              </thead>
              <tbody>
                <tr className="border-b border-gray-100">
                  <td className="py-3 px-4">
                    <Button variant="link" className="text-blue-600 p-0 h-auto font-normal">
                      Glovis_Manifest
                    </Button>
                  </td>
                  <td className="py-3 px-4">
                    <Button variant="link" className="text-blue-600 p-0 h-auto font-normal">
                      Glovis_PortNetSummary
                    </Button>
                  </td>
                  <td className="py-3 px-4">
                    <div className="flex items-center gap-2">
                      <div className="flex-1 h-2 bg-gray-200 rounded-full overflow-hidden max-w-[200px]">
                        <div className="h-full bg-green-500" style={{ width: "100%" }} />
                      </div>
                      <span className="text-sm text-gray-900 font-medium">100</span>
                    </div>
                  </td>
                  <td className="py-3 px-4 text-sm text-gray-900">No Errors</td>
                  <td className="py-3 px-4">
                    <div className="flex gap-2 text-sm">
                      <Button variant="link" size="sm" className="text-blue-600 p-0 h-auto">
                        View/Edit
                      </Button>
                      <span className="text-gray-300">|</span>
                      <Button variant="link" size="sm" className="text-blue-600 p-0 h-auto">
                        Download
                      </Button>
                      <span className="text-gray-300">|</span>
                      <Button variant="link" size="sm" className="text-red-600 p-0 h-auto">
                        Delete
                      </Button>
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        {/* Actions */}
        <div className="flex justify-between items-center">
          <Button variant="outline" asChild>
            <Link href={`/shipments/${shipment.id}/portnet-submission`}>Back to PortNet Submission</Link>
          </Button>
          <Button asChild>
            <Link href={`/shipments/${shipment.id}/discharge`}>Proceed to Discharge Summary</Link>
          </Button>
        </div>
      </div>
    </div>
  )
}
