import type { Shipment, Alert, Document, BillOfLading, CargoAllocationPlan, Email, EmailThread } from "@/types"

// Seeded random for consistent confidence scores
function seededRandom(seed: string): number {
  let hash = 0
  for (let i = 0; i < seed.length; i++) {
    hash = (hash << 5) - hash + seed.charCodeAt(i)
    hash = hash & hash
  }
  const x = Math.sin(Math.abs(hash)) * 10000
  return x - Math.floor(x)
}

export const mockShipments: Shipment[] = [
  {
    id: "2025-001",
    shipmentNumber: "2025-001",
    transactionStartTime: "22nd Aug 2025, 12:00",
    vesselName: "Jiuyang Bonanza V.007",
    eta: "1st Oct 2025, 14:00",
    shipPrincipal: "Glovis",
    changeOfDestination: null,
    status: "pre-submission",
    createdOn: "22 Aug 2025",
    stages: {
      preSubmission: true,
      portnetSubmission: false,
      preArrivalValidation: false,
      dischargeSummary: false,
      vesselArrival: false,
    },
  },
  {
    id: "2025-002",
    shipmentNumber: "2025-002",
    transactionStartTime: "25th Aug 2025, 15:00",
    vesselName: "Morning Composer",
    eta: "25th Oct 2025, 12:00",
    shipPrincipal: "Eukor",
    changeOfDestination: null,
    status: "portnet-submission",
    createdOn: "25 Aug 2025",
    stages: {
      preSubmission: true,
      portnetSubmission: true,
      preArrivalValidation: false,
      dischargeSummary: false,
      vesselArrival: false,
    },
  },
  {
    id: "2025-003",
    shipmentNumber: "2025-003",
    transactionStartTime: "27th Aug 2025, 15:00",
    vesselName: "OPAL Ace",
    eta: "28th Oct 2025, 12:00",
    shipPrincipal: "MOL",
    changeOfDestination: null,
    status: "pre-arrival-validation",
    createdOn: "27 Aug 2025",
    stages: {
      preSubmission: true,
      portnetSubmission: true,
      preArrivalValidation: true,
      dischargeSummary: false,
      vesselArrival: false,
    },
  },
  {
    id: "2025-004",
    shipmentNumber: "2025-004",
    transactionStartTime: "15th Aug 2025, 09:00",
    vesselName: "Pacific Glory",
    eta: "20th Sept 2025, 08:00",
    shipPrincipal: "KMTC",
    changeOfDestination: null,
    status: "completed",
    createdOn: "15 Aug 2025",
    stages: {
      preSubmission: true,
      portnetSubmission: true,
      preArrivalValidation: true,
      dischargeSummary: true,
      vesselArrival: true,
    },
  },
]

export const mockAlerts: Alert[] = [
  {
    id: "alert-1",
    type: "error",
    title: "Low AI Confidence Score",
    description: "Bill of Lading BL documents for Vessel Jiuyang Bonanza V.008",
    shipmentNumber: "2025-002",
    timestamp: "1st Oct 2025, 15:00",
    dismissed: false,
  },
  {
    id: "alert-2",
    type: "error",
    title: "Cargo Manifest Rejected by Docs Team Checker",
    description: "Cargo Manifest for Vessel Jiuyang Bonanza V.007",
    shipmentNumber: "2025-001",
    timestamp: "29th Sept 2025, 13:00",
    dismissed: false,
  },
]

export const mockDocuments: Record<string, Document[]> = {
  "2025-001": [
    {
      id: "doc-1",
      shipmentId: "2025-001",
      documentName: "Bill_of_Lading_001",
      documentType: "BL",
      aiConfidenceScore: 100,
      lastUpdated: "8/09/2025 12:00",
      numberOfUnits: 5,
    },
    {
      id: "doc-2",
      shipmentId: "2025-001",
      documentName: "Bill_of_Lading_002",
      documentType: "BL",
      aiConfidenceScore: 100,
      lastUpdated: "8/09/2025 12:00",
      numberOfUnits: 5,
    },
    {
      id: "doc-3",
      shipmentId: "2025-001",
      documentName: "Bill_of_Lading_003",
      documentType: "BL",
      aiConfidenceScore: 100,
      lastUpdated: "8/09/2025 12:00",
      numberOfUnits: 5,
    },
    {
      id: "doc-4",
      shipmentId: "2025-001",
      documentName: "Bill_of_Lading_004",
      documentType: "BL",
      aiConfidenceScore: 100,
      lastUpdated: "8/09/2025 12:00",
      numberOfUnits: 5,
    },
    {
      id: "doc-5",
      shipmentId: "2025-001",
      documentName: "Bill_of_Lading_005",
      documentType: "BL",
      aiConfidenceScore: 100,
      lastUpdated: "8/09/2025 12:00",
      numberOfUnits: 3,
    },
  ],
  "2025-004": [
    {
      id: "doc-4-1",
      shipmentId: "2025-004",
      documentName: "Bill_of_Lading_PG_001",
      documentType: "BL",
      aiConfidenceScore: 98,
      lastUpdated: "15/08/2025 10:00",
      numberOfUnits: 8,
    },
    {
      id: "doc-4-2",
      shipmentId: "2025-004",
      documentName: "Bill_of_Lading_PG_002",
      documentType: "BL",
      aiConfidenceScore: 100,
      lastUpdated: "15/08/2025 10:00",
      numberOfUnits: 7,
    },
    {
      id: "doc-4-3",
      shipmentId: "2025-004",
      documentName: "VIN_List_Pacific_Glory",
      documentType: "VIN_LIST",
      aiConfidenceScore: 100,
      lastUpdated: "16/08/2025 14:00",
      numberOfUnits: 15,
    },
    {
      id: "doc-4-4",
      shipmentId: "2025-004",
      documentName: "BL_List_Pacific_Glory",
      documentType: "BL_LIST",
      aiConfidenceScore: 100,
      lastUpdated: "16/08/2025 14:00",
    },
    {
      id: "doc-4-5",
      shipmentId: "2025-004",
      documentName: "Cargo_Manifest_Final",
      documentType: "MANIFEST",
      aiConfidenceScore: 100,
      lastUpdated: "18/08/2025 16:00",
    },
    {
      id: "doc-4-6",
      shipmentId: "2025-004",
      documentName: "Discharge_Summary",
      documentType: "PORTNET",
      aiConfidenceScore: 100,
      lastUpdated: "22/09/2025 11:00",
    },
  ],
}

export const mockBillsOfLading: Record<string, BillOfLading[]> = {
  "2025-001": [
    {
      id: "bl-1",
      shipmentId: "2025-001",
      documentName: "Bill_of_Lading_001",
      documentType: "BL",
      blNumber: "HDGLCNS0634447",
      units: 5,
      aiConfidenceScore: 100,
      matchScoreBL: 100,
      matchScoreVIN: 100,
      lastUpdated: "8/09/2025 12:00",
    },
    {
      id: "bl-2",
      shipmentId: "2025-001",
      documentName: "Bill_of_Lading_002",
      documentType: "BL",
      blNumber: "HDGLCNS0634567",
      units: 5,
      aiConfidenceScore: 100,
      matchScoreBL: 100,
      matchScoreVIN: 100,
      lastUpdated: "8/09/2025 12:00",
    },
    {
      id: "bl-3",
      shipmentId: "2025-001",
      documentName: "Bill_of_Lading_003",
      documentType: "BL",
      blNumber: "HDGLCNS0634571",
      units: 5,
      aiConfidenceScore: 100,
      matchScoreBL: 100,
      matchScoreVIN: 100,
      lastUpdated: "8/09/2025 12:00",
    },
    {
      id: "bl-4",
      shipmentId: "2025-001",
      documentName: "Bill_of_Lading_004",
      documentType: "BL",
      blNumber: "HDGLKRAU0635562",
      units: 5,
      aiConfidenceScore: 100,
      matchScoreBL: 100,
      matchScoreVIN: 100,
      lastUpdated: "8/09/2025 12:00",
    },
    {
      id: "bl-5",
      shipmentId: "2025-001",
      documentName: "Bill_of_Lading_005",
      documentType: "BL",
      blNumber: "HDGLKRB0635738",
      units: 3,
      aiConfidenceScore: 100,
      matchScoreBL: 100,
      matchScoreVIN: 100,
      lastUpdated: "8/09/2025 12:00",
    },
  ],
  "2025-004": [
    {
      id: "bl-4-1",
      shipmentId: "2025-004",
      documentName: "Bill_of_Lading_PG_001",
      documentType: "BL",
      blNumber: "KMTCPG2025001",
      units: 8,
      aiConfidenceScore: 98,
      matchScoreBL: 100,
      matchScoreVIN: 100,
      lastUpdated: "15/08/2025 10:00",
    },
    {
      id: "bl-4-2",
      shipmentId: "2025-004",
      documentName: "Bill_of_Lading_PG_002",
      documentType: "BL",
      blNumber: "KMTCPG2025002",
      units: 7,
      aiConfidenceScore: 100,
      matchScoreBL: 100,
      matchScoreVIN: 100,
      lastUpdated: "15/08/2025 10:00",
    },
  ],
}

export const mockCargoAllocationPlan: Record<string, CargoAllocationPlan> = {
  "2025-001": {
    id: "cap-1",
    shipmentId: "2025-001",
    totalUnits: 50,
    aiConfidenceScore: 86,
    documentName: "Cargo_Allocation_Plan",
  },
  "2025-004": {
    id: "cap-4",
    shipmentId: "2025-004",
    totalUnits: 15,
    aiConfidenceScore: 95,
    documentName: "Cargo_Allocation_Plan_Pacific_Glory",
  },
}

// Generate confidence score based on seed
export function generateConfidence(seed: string, bias: "high" | "medium" | "low" = "high"): number {
  const random = seededRandom(seed)

  if (bias === "high") {
    return Math.round((0.85 + random * 0.15) * 100)
  } else if (bias === "medium") {
    return Math.round((0.7 + random * 0.2) * 100)
  } else {
    return Math.round((0.5 + random * 0.35) * 100)
  }
}

export const mockEmails: Email[] = [
  {
    id: "email-1",
    from: "glovis.shipping@example.com",
    to: "operations@sscl.com.sg",
    subject: "Shipment Notification - Morning Composer",
    body: "We request your support in coordinating the bunkering services as per the following details.",
    receivedAt: "22 Aug 2025, 17:30",
    status: "processed",
    priority: "high",
    shipmentId: "2025-001",
    attachments: [
      {
        id: "att-1",
        fileName: "Bunkering_Request.pdf",
        fileType: "application/pdf",
        fileSize: 245000,
        documentType: "PORTNET",
        aiConfidenceScore: 100,
        extracted: true,
      },
    ],
    hasShipmentDocuments: true,
    aiProcessed: true,
    tags: ["Shipment Docs", "AI Processed", "2025-001"],
    category: "Bunkering",
  },
  {
    id: "email-2",
    from: "PSA@example.com",
    to: "operations@sscl.com.sg",
    subject: "Shipment Notification - Jiuyang Bonanza",
    body: "Please find attached Yard Plan.",
    receivedAt: "25 Aug 2025, 14:10",
    status: "processed",
    priority: "high",
    shipmentId: "2025-002",
    attachments: [
      {
        id: "att-4",
        fileName: "Yard_Plan.pdf",
        fileType: "application/pdf",
        fileSize: 198000,
        documentType: "YARD_PLAN",
        aiConfidenceScore: 100,
        extracted: true,
      },
    ],
    hasShipmentDocuments: true,
    aiProcessed: true,
    tags: ["Shipment Docs", "AI Processed", "2025-002"],
    category: "Discharge",
  },
  {
    id: "email-3",
    from: "mol.shipping@example.com",
    to: "operations@sscl.com.sg",
    subject: "Shipment Notification - My Glovis Splendor",
    body: "Vessel ETA Singapore: 1400h Aug 25",
    receivedAt: "27 Aug 2025, 09:00",
    status: "read",
    priority: "normal",
    shipmentId: "2025-003",
    attachments: [],
    hasShipmentDocuments: false,
    aiProcessed: true,
    tags: ["AI Processed", "2025-003"],
    category: "Loading",
  },
  {
    id: "email-4",
    from: "kmtc.operations@example.com",
    to: "operations@sscl.com.sg",
    subject: "Shipment Documents - Container Vessel KM-2025-004",
    body: "Please find attached shipment documents for processing.",
    receivedAt: "28 Aug 2025, 16:45",
    status: "unread",
    priority: "high",
    shipmentId: "2025-004",
    attachments: [
      {
        id: "att-5",
        fileName: "Shipping_Manifest.pdf",
        fileType: "application/pdf",
        fileSize: 312000,
        documentType: "MANIFEST",
        extracted: false,
      },
    ],
    hasShipmentDocuments: true,
    aiProcessed: false,
    tags: ["Pending"],
    category: "Documentation",
  },
  {
    id: "email-5",
    from: "kmtc.shipping@example.com",
    to: "operations@sscl.com.sg",
    subject: "Initial Shipment Documents - Pacific Glory V.2025-004",
    body: "Please find attached the initial Bill of Lading documents and Cargo Allocation Plan for vessel Pacific Glory, ETA 20th September 2025.",
    receivedAt: "15 Aug 2025, 09:15",
    status: "processed",
    priority: "high",
    shipmentId: "2025-004",
    attachments: [
      {
        id: "att-6",
        fileName: "Bill_of_Lading_PG_001.pdf",
        fileType: "application/pdf",
        fileSize: 234000,
        documentType: "BL",
        aiConfidenceScore: 98,
        extracted: true,
      },
      {
        id: "att-7",
        fileName: "Bill_of_Lading_PG_002.pdf",
        fileType: "application/pdf",
        fileSize: 241000,
        documentType: "BL",
        aiConfidenceScore: 100,
        extracted: true,
      },
      {
        id: "att-8",
        fileName: "Cargo_Allocation_Plan_Pacific_Glory.xlsx",
        fileType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        fileSize: 167000,
        documentType: "PORTNET",
        aiConfidenceScore: 95,
        extracted: true,
      },
    ],
    hasShipmentDocuments: true,
    aiProcessed: true,
    tags: ["Shipment Docs", "AI Processed", "2025-004"],
    category: "Documentation",
  },
  {
    id: "email-6",
    from: "kmtc.shipping@example.com",
    to: "operations@sscl.com.sg",
    subject: "VIN and BL Lists - Pacific Glory",
    body: "Attached are the VIN List and BL List for validation purposes.",
    receivedAt: "16 Aug 2025, 14:20",
    status: "processed",
    priority: "high",
    shipmentId: "2025-004",
    attachments: [
      {
        id: "att-9",
        fileName: "VIN_List_Pacific_Glory.xlsx",
        fileType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        fileSize: 89000,
        documentType: "VIN_LIST",
        aiConfidenceScore: 100,
        extracted: true,
      },
      {
        id: "att-10",
        fileName: "BL_List_Pacific_Glory.xlsx",
        fileType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        fileSize: 76000,
        documentType: "BL_LIST",
        aiConfidenceScore: 100,
        extracted: true,
      },
    ],
    hasShipmentDocuments: true,
    aiProcessed: true,
    tags: ["Shipment Docs", "AI Processed", "2025-004"],
    category: "Documentation",
  },
  {
    id: "email-7",
    from: "operations@sscl.com.sg",
    to: "kmtc.shipping@example.com",
    subject: "RE: Cargo Manifest Approved - Pacific Glory",
    body: "Your cargo manifest has been reviewed and approved. The vessel is cleared for discharge operations.",
    receivedAt: "18 Aug 2025, 16:30",
    status: "processed",
    priority: "normal",
    shipmentId: "2025-004",
    attachments: [],
    hasShipmentDocuments: false,
    aiProcessed: true,
    tags: ["Outgoing", "2025-004"],
    category: "Discharge",
  },
  {
    id: "email-8",
    from: "psa.operations@example.com",
    to: "operations@sscl.com.sg",
    subject: "Discharge Summary - Pacific Glory Completed",
    body: "Discharge operations for Pacific Glory have been completed. Summary attached.",
    receivedAt: "22 Sept 2025, 11:00",
    status: "processed",
    priority: "normal",
    shipmentId: "2025-004",
    attachments: [
      {
        id: "att-11",
        fileName: "Discharge_Summary_Pacific_Glory.pdf",
        fileType: "application/pdf",
        fileSize: 198000,
        documentType: "PORTNET",
        aiConfidenceScore: 100,
        extracted: true,
      },
    ],
    hasShipmentDocuments: true,
    aiProcessed: true,
    tags: ["Shipment Docs", "AI Processed", "2025-004"],
    category: "Discharge",
  },
]

export const mockEmailThreads: Record<string, EmailThread> = {
  "2025-001": {
    id: "thread-1",
    shipmentId: "2025-001",
    emails: [mockEmails[0]],
    participants: ["glovis.shipping@example.com", "operations@sscl.com.sg"],
    lastActivity: "22 Aug 2025, 10:30",
  },
  "2025-002": {
    id: "thread-2",
    shipmentId: "2025-002",
    emails: [mockEmails[1]],
    participants: ["eukor.logistics@example.com", "operations@sscl.com.sg"],
    lastActivity: "25 Aug 2025, 14:15",
  },
  "2025-004": {
    id: "thread-4",
    shipmentId: "2025-004",
    emails: [mockEmails[4], mockEmails[5], mockEmails[6], mockEmails[7]],
    participants: ["kmtc.shipping@example.com", "operations@sscl.com.sg", "psa.operations@example.com"],
    lastActivity: "22 Sept 2025, 11:00",
  },
}
